### ISSUE TITLE
is it possible to extend the bundle?

### ISSUE THREAD

**Issue by perryxp** [PRayno/CasAuthBundle#1]
I've installed your bundle in my project, but I need to override your service because it uses a file_get_content of an url (it's not possible in my environment).

When I extend your CasAuthenticator class to override the getCredentials method, I get an error because attributes are private. Was your intention to avoid it being extended?
Do you want me to modify the visibility for those properties?

Thank you for your work on this bundle!

**Comment by webmastard** [comment]
Hi, @perryxp 
I had the same problem and I have solved like this
In your class add $config param : 
`protected $config;`
and override __construct method

```
    public function __construct($config)
    {
        $this->config = $config;
        parent::__construct($config);
    }
```

and in method getCredentials use 
`$this->config['needed_parameter']`

**Comment by PRayno** [comment]
Hi,
file_get_content is definitely not a good idea.
I should use Guzzle to send the http request to the CAS server. I'll try to find some time to fix my code.
Thanks for using this bundle !

**Comment by PRayno** [comment]
I've just updated the bundle. Thanks for your code @webmastard !

**Comment by perryxp** [comment]
Thanks for your work @PRayno!!
