### ISSUE TITLE
Authentication sso is true but role is false ??

### ISSUE THREAD

**Issue by sebius77** [PRayno/CasAuthBundle#10]
Hi, I works on Symfony 4 and I want use a SSO Authentication. I saw your library . I saw that it work with guard. I test it and the redirection work to the sso but I don't know how to do when authentication is true but the role ROLE_USER don't exist. On the server symfony I have an error : Access denied, the user is not fully authenticated and redirect user to the sso but he's yet connected. I would like to redirect to template with error message. I need your help to understand.

Next, I would like to adapt your library to Symfony 4.

Thanks.

**Comment by junowilderness** [comment]
Create a user class implementing UserInterface and a user provider for it implementing UserProviderInterface. Use UserProviderInterface::loadUserByUsername() to add default roles. Specify this custom provider class id for "cas":

In security.yml:

```yaml
security:

    providers:
        cas:
          id: App\User\MyUserProvider
```

**Comment by junowilderness** [comment]
I just now submitted PR #11 to make this compatible with Symfony 4.

**Comment by sebius77** [comment]
I'll test as soon as I can. Thank you very much

**Comment by junowilderness** [comment]
@sebius77 That PR is working fine for me on two SF4 apps.

For easy testing, add this to the app's composer.json:
```
    "repositories": [
        {
            "type": "vcs",
            "url":  "git@github.com:cilefen/CasAuthBundle.git"
        }
    ]
```

And require the PR's branch:

    composer require prayno/casauth-bundle:dev-sf4-compatibility

**Comment by junowilderness** [comment]
I should add that you could also specify default roles in the custom user class implementing UserInterface.

**Comment by junowilderness** [comment]
@sebius77 It's been merged so only this is needed:

    composer require prayno/casauth-bundle:dev-master

**Comment by PRayno** [comment]
Thanks for this PR @cilefen , I just couldn't find time to do this work.
I think it might also require symfony/security-bundle to get the security.yaml file

**Comment by junowilderness** [comment]
I am happy to help. 

I think no on security-bundle unless this bundle absolutely requires it.

**Comment by PRayno** [comment]
I published a new version on packagist so you just need : 

`composer require prayno/cas-authbundle`
