### ISSUE TITLE
Attempted to call an undefined method named "getRootNode"

### ISSUE THREAD

**Issue by lohamdev** [PRayno/CasAuthBundle#22]
Hi,

I tried to install your bundle and everything was OK.

But when i start symfony project, nothing works and i have the current error:

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getRootNode" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder". in /vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/DependencyInjection/Configuration.php:22

Could you help me ?

I'm on linux and i use Symfony 3.4

Thanks

**Comment by lohamdev** [comment]
I partially solved my problem:

I install the previous release of the bundle (1.3), and everything works fine

I guest there is a problem with symfony 3 and the last release of CasAuthBundle

thanks for your work

Regards

**Comment by PRayno** [comment]
Hi,
There was a backward compatibility issue on the last release. I just fixed it with the 1.3.2 release.
Thanks for your comment
