### ISSUE TITLE
Can not authenticate with Symfony 4.4, OK with 4.3

### ISSUE THREAD

**Issue by julienbdx** [PRayno/CasAuthBundle#29]
With Symfony 4.3, it works like a charm.

When I update to 4.4, I have a redirect loop and I can not be authenticate.
When I look in dev logs, I find :

> [2020-03-04 11:30:14] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"cas","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
> ...
> [2020-03-04 11:30:14] doctrine.DEBUG: SELECT ...
> [2020-03-04 11:30:14] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"xxxxxxxx\", authenticated=true, roles=\"ROLE_ADMIN_\"))","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
> [2020-03-04 11:30:14] security.DEBUG: Guard authenticator set success response. {"response":"..."}
> [2020-03-04 11:30:14] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
> [2020-03-04 11:30:14] security.DEBUG: The "PRayno\CasAuthBundle\Security\CasAuthenticator" authenticator set the response. Any later authenticator will not be called {"authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
> [2020-03-04 11:30:14] security.DEBUG: Stored the security token in the session. {"key":"_security_cas"} []
> [2020-03-04 11:30:14] request.INFO: Matched route "diret". 
> [2020-03-04 11:30:14] security.DEBUG: Read existing security token from the session. {"key":"_security_cas","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
> [2020-03-04 11:30:14] doctrine.DEBUG: SELECT...
> **[2020-03-04 11:30:14] security.DEBUG: Cannot refresh token because user has changed. {"username":"xxxxxxxx","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []**
> **[2020-03-04 11:30:14] security.DEBUG: Token was deauthenticated after trying to refresh it. [] []**
> [2020-03-04 11:30:14] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"cas","authenticators":1} []
> [2020-03-04 11:30:14] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"cas","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
**> [2020-03-04 11:30:14] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"cas","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []**
> [2020-03-04 11:30:14] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
> [2020-03-04 11:30:14] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point.

Any idea how to solve this problem ?
Thanks !

**Comment by micayael** [comment]
Hi @julienbdx, do you found a solution for this?
