### ISSUE TITLE
Logging out CAS session

### ISSUE THREAD

**Issue by vctls** [PRayno/CasAuthBundle#3]
Not sure if I can ask this here, but anyway:

I see the configuration includes a `server_logout_url` option,
but does the bundle allow logging out of CAS in any way?

Or do I have to implement my own LoggoutSuccessHandler?

**Comment by PRayno** [comment]
Hi,
This bundle doesn't do any logout.
You must implement your own handler and use the server_logout_url option to kill the CAS session.

Sorry for this late reply, it was vacation time for me !

Pierre

**Comment by vctls** [comment]
No problem!
That's what I did.

Thanks for the reply.
