### ISSUE TITLE
Open to contributors?

### ISSUE THREAD

**Issue by arderyp** [PRayno/CasAuthBundle#9]
Hello.  Sorry if this is the wrong place to ask, but I didn't know how else to contact you.  I am using the now defunct [BeSimpleSsoAuthBundle](https://github.com/BeSimple/BeSimpleSsoAuthBundle) and am looking for a S3 friendly replacement.  I was going to build my own approach using Guard, but it looks like you all have already done a nice job here, and I generally think it would be better to have a public open source CAS option out there with active users and developers.  So thank you for this project!  Are you open to other developers contributing to the project?  I see there are 3 issues open right now.  Those aside, do you feel the bundle is currently stable and production-ready?  Are you running it in production?  Do you know if other third parties are running it?

Thanks,
Phil

**Comment by PRayno** [comment]
Hi Phil,
That's exactly the reason why I created this project when migrating to SF 2.8.
I work for a French University with 40000+ users and I'm using this bundle in 5 apps in production right now without any issues.
Basically, it lacks PHP Unit Tests and more detailed requirements (it currently requires the whole symfony/symfony package ...). 
I would be pleased to have other developers helping me out as I don't have much time to spend on this project. The main philosophy is to keep it as simple as possible and just do what it's supposed to do : authenticating users.

Thanks for your interest is this projet !

Pierre

**Comment by arderyp** [comment]
Thanks for the quick response Pierre.  I will keep you posted as to whether we end up adopting CasAuthBundle.  One more quick question, if you don't mind, do you have any thoughts on the popular [phpCAS](https://github.com/Jasig/phpCAS) package and/or did you choose your Guzzle approach over phpCAS for any particular reason(s)?

Thanks again!
Phil

**Comment by arderyp** [comment]
just wanted to check in on this.  Thanks

**Comment by PRayno** [comment]
Hi,
Sorry for the late reply, it was vacation time for me !
I just wanted to keep my bundle as simple as possible and the phpCAS bundle seemed to be a lot of code for a simple http request.
However, if some features are better supported or if needed on different environment, it should be pretty easy to use phpCAS instead of Guzzle.

Pierre

**Comment by arderyp** [comment]
Awesome, thanks @PRayno! I agree with you whole heartedly that simple is the best way to go.  I will keep you posted if we end up adopting this and look forward to contributing if that is the case.  Thanks again.
